---
- name: Install dependencies for Singularity
  apt:
    name: build-essential,uuid-dev,libgpgme-dev,squashfs-tools,libseccomp-dev,wget,pkg-config,git,cryptsetup-bin
    state: latest

- name: Create temporary directory for singularity files
  file:
    path: "{{ singularity_temp_path }}/"
    state: directory
    mode: "0755"

- name: Download singularity
  get_url:
    url: "{{ singularity_url }}"
    dest: "{{ singularity_temp_path }}/"

- name: Unpack singularity
  unarchive:
    src: "{{ singularity_temp_path }}/{{ singularity_fname }}"
    dest: "{{ singularity_temp_path }}/"
    remote_src: yes
    list_files: yes

- name: Configure singularity
  command:
    chdir: "{{ singularity_src_path }}/"
    cmd: "./mconfig"

- name: Build singularity
  command:
    chdir: "{{ singularity_src_path }}/"
    cmd: "make -C ./builddir"

- name: Install singularity
  command:
    chdir: "{{ singularity_src_path }}/"
    cmd: "sudo make -C ./builddir install"

- name: Delete temporary files
  file:
    path: "{{ singularity_temp_path }}"
    state: absent

- name: Ensure singularity works
  command: "singularity --version"
